name: anselme_irumva_individual_assignment_2
description: "Notes App with Firebase Authentication"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  
  # Firebase dependencies
  firebase_core: ^3.15.1
  firebase_auth: ^5.3.3
  cloud_firestore: ^5.5.0
  
  # State management
  flutter_bloc: ^8.1.6
  equatable: ^2.0.5
  
  # UI dependencies
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
